from __future__ import annotations

import os
import sqlite3
import csv
from pathlib import Path

import pytest

from disk_cleanup.indexer.database import import_wiztree_csv
from disk_cleanup.scanner.csv_parser import stream_wiztree_csv
from disk_cleanup.scanner.walk import walk_windows_tree


HEADER = (
    "File Name,Size,Allocated,Modified,Attributes,Files,Folders,"
    "DRIVECAPACITY,FREESPACE,USEDSPACE,RESERVEDSPACE\n"
)


def _write_csv(path: Path, rows: list[list[object]], encoding: str) -> None:
    with path.open("w", encoding=encoding, newline="") as handle:
        handle.write("Generated by WizTree\n")
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(HEADER.rstrip().split(","))
        writer.writerows(rows)


def test_stream_parser_reads_utf16_incrementally(tmp_path: Path) -> None:
    csv_path = tmp_path / "scan.csv"
    _write_csv(
        csv_path,
        [
            ["C:\\", 10, 16, "2026/01/01", 0, 1, 0, 100, 20, 80, 0],
            ["C:\\cache.bin", 10, 16, "2026/01/01", 0, 0, 0, "", "", "", ""],
        ],
        "utf-16",
    )

    with stream_wiztree_csv(csv_path) as (metadata, nodes):
        iterator = iter(nodes)
        assert metadata.root_path == "C:\\"
        assert next(iterator).node_type == "directory"
        assert next(iterator).full_path == "C:\\cache.bin"
        with pytest.raises(StopIteration):
            next(iterator)


def test_import_batches_unsorted_rows_and_backfills_parents(tmp_path: Path) -> None:
    csv_path = tmp_path / "scan.csv"
    _write_csv(
        csv_path,
        [
            ["C:\\cache.bin", 10, 16, "2026/01/01", 0, 0, 0, "", "", "", ""],
            ["C:\\", 10, 16, "2026/01/01", 0, 1, 0, 100, 20, 80, 0],
        ],
        "utf-8",
    )
    db_path = tmp_path / "index.sqlite3"

    summary = import_wiztree_csv(csv_path, db_path, batch_size=1)

    assert summary.rows == 2
    with sqlite3.connect(db_path) as conn:
        parent = conn.execute(
            """
            SELECT parent.full_path
            FROM nodes AS child
            JOIN nodes AS parent ON parent.id = child.parent_id
            WHERE child.full_path = 'C:\\cache.bin'
            """
        ).fetchone()
    assert parent == ("C:\\",)


def test_scandir_walk_does_not_follow_links_and_obeys_budget(tmp_path: Path) -> None:
    root = tmp_path / "root"
    root.mkdir()
    (root / "a.txt").write_bytes(b"a")
    nested = root / "nested"
    nested.mkdir()
    (nested / "b.txt").write_bytes(b"bb")
    link = root / "link"
    try:
        os.symlink(nested, link, target_is_directory=True)
    except (OSError, NotImplementedError):
        link = None

    complete_walk = walk_windows_tree(root)
    complete_nodes = list(complete_walk)
    budget_walk = walk_windows_tree(root, max_entries=2)
    budget_nodes = list(budget_walk)

    assert len(budget_nodes) <= 2
    assert budget_walk.stats.truncated is True
    assert budget_walk.stats.truncation_reason == "entry_budget"
    if link is not None:
        assert all(Path(node.full_path.rstrip("\\/")) != link for node in complete_nodes)
        assert complete_walk.stats.skipped_reparse_points == 1
