from __future__ import annotations

from pathlib import Path

from disk_cleanup.indexer.database import import_wiztree_csv
from disk_cleanup.indexer.queries import extension_summary, largest_files, top_children
from disk_cleanup.scanner.csv_parser import read_wiztree_csv


def test_parse_wiztree_csv_fixture() -> None:
    fixture = Path(__file__).parent / "fixtures" / "sample-wiztree.csv"

    metadata, nodes = read_wiztree_csv(fixture)

    assert metadata.root_path == "C:\\"
    assert len(nodes) == 9
    assert sum(1 for node in nodes if node.node_type == "directory") == 5
    assert sum(1 for node in nodes if node.node_type == "file") == 4
    root = next(node for node in nodes if node.full_path == "C:\\")
    file_node = next(node for node in nodes if node.full_path == "C:\\Users\\ExampleUser\\b.zip")
    assert root.allocated_bytes == 0
    assert root.subtree_allocated_bytes == 8192
    assert file_node.allocated_bytes == 3072
    assert file_node.parent_path == "C:\\Users\\ExampleUser\\"
    assert file_node.extension == ".zip"


def test_import_wiztree_csv_to_sqlite(tmp_path: Path) -> None:
    fixture = Path(__file__).parent / "fixtures" / "sample-wiztree.csv"
    db_path = tmp_path / "index.sqlite3"

    summary = import_wiztree_csv(fixture, db_path)

    assert summary.rows == 9
    assert summary.files == 4
    assert summary.folders == 5
    assert summary.max_depth == 6
    assert summary.total_file_allocated_bytes == 18432

    root_children = top_children(db_path, summary.scan_id, "C:\\", limit=10)
    assert [row["full_path"] for row in root_children] == ["C:\\Users\\", "C:\\Temp\\"]

    files = largest_files(db_path, summary.scan_id, limit=2)
    assert [row["full_path"] for row in files] == [
        "C:\\Users\\ExampleUser\\AppData\\Local\\Temp\\cache.tmp",
        "C:\\Users\\ExampleUser\\b.zip",
    ]

    extensions = extension_summary(db_path, summary.scan_id, limit=5)
    assert extensions[0]["extension"] == ".tmp"


def test_reads_english_wiztree_header(tmp_path: Path) -> None:
    csv_path = tmp_path / "english.csv"
    csv_path.write_text(
        "Generated by WizTree\n"
        "File Name,Size,Allocated,Modified,Attributes,Files,Folders,DRIVECAPACITY,FREESPACE,USEDSPACE,RESERVEDSPACE\n"
        '"C:\\",100,100,2026/01/01 00:00:00,0,0,0,1000,500,500,0\n',
        encoding="utf-8",
    )
    metadata, nodes = read_wiztree_csv(csv_path)
    assert metadata.root_path == "C:\\"
    assert len(nodes) == 1
