[CmdletBinding()]
param(
    [ValidateSet("scan", "clean")]
    [string]$Mode = "scan",
    [string]$CsvPath,
    [string]$Target = "C:",
    [string]$WizTreePath,
    [string]$Python = "python",
    [ValidateRange(0, 100)]
    [int]$ExportMaxDepth = 0,
    [switch]$NoOpen
    ,[string]$RunId
    ,[string[]]$CandidateId
    ,[string]$PlanHash
    ,[string]$ApprovalCode
)

$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
$OutputEncoding = [Console]::OutputEncoding
$env:PYTHONUTF8 = "1"
$ProjectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$RunRoot = Join-Path ([IO.Path]::GetTempPath()) ("DiskCleanupSkill\run-" + [Guid]::NewGuid().ToString("N"))
$TempBase = Join-Path ([IO.Path]::GetTempPath()) "DiskCleanupSkill"

function Convert-ToTomlPath([string]$Value) {
    if ($null -eq $Value) { return "" }
    return $Value.Replace('\', '\\')
}

function Resolve-WizTreeExecutable {
    if ($script:WizTreePath -and (Test-Path -LiteralPath $script:WizTreePath -PathType Leaf)) {
        $script:WizTreePath = (Resolve-Path -LiteralPath $script:WizTreePath).Path
        return
    }
    $candidates = @($env:DISK_CLEAN_WIZTREE, "C:\Program Files\WizTree\WizTree64.exe")
    $found = $candidates | Where-Object { $_ -and (Test-Path -LiteralPath $_ -PathType Leaf) } | Select-Object -First 1
    if (-not $found) {
        $command = Get-Command "WizTree64.exe" -ErrorAction SilentlyContinue
        if ($command) { $found = $command.Source }
    }
    if ($found) { $script:WizTreePath = (Resolve-Path -LiteralPath $found).Path }
}

function Assert-RunRootIsDisposable([string]$Path) {
    $fullPath = [IO.Path]::GetFullPath($Path)
    $fullBase = [IO.Path]::GetFullPath($TempBase)
    if (-not $fullPath.StartsWith($fullBase, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Refuse to remove path outside temp workspace: $fullPath"
    }
}

function Export-WizTreeCsv([string]$OutputPath) {
    Resolve-WizTreeExecutable
    if (-not (Test-Path -LiteralPath $WizTreePath)) {
        throw "WizTree executable not found: $WizTreePath"
    }
    if ($Target.Contains('"') -or $Target.StartsWith('/') -or $Target.StartsWith('\\')) {
        throw "Target must be an absolute local path: $Target"
    }
    if ($Target -match '^[A-Za-z]:$') { $script:Target = $Target + '\' }
    if (-not [IO.Path]::IsPathRooted($Target)) { throw "Target must be absolute: $Target" }

    $adminValue = if ($Admin) { "1" } else { "0" }
    $arguments = @(
        $Target,
        "/export=$OutputPath",
        "/admin=$adminValue",
        "/exportfolders=1",
        "/exportfiles=1",
        "/sortby=2",
        "/exportdrivecapacity=1",
        "/exportmaxdepth=$ExportMaxDepth"
    )
    $startInfo = [System.Diagnostics.ProcessStartInfo]::new()
    $startInfo.FileName = (Resolve-Path -LiteralPath $WizTreePath).Path
    $startInfo.UseShellExecute = $false
    $startInfo.CreateNoWindow = $true
    if ($null -ne $startInfo.ArgumentList) {
        foreach ($argument in $arguments) { [void]$startInfo.ArgumentList.Add($argument) }
    }
    else {
        # Windows PowerShell 5.1/.NET Framework has no usable ArgumentList API.
        # Target rejects quotes and all other values are generated by this script.
        $startInfo.Arguments = ($arguments | ForEach-Object {
            if ($_ -match '\s') { '"' + $_ + '"' } else { $_ }
        }) -join ' '
    }
    Write-Verbose "Starting read-only WizTree CSV export."
    $process = [System.Diagnostics.Process]::Start($startInfo)
    $process.WaitForExit()
    if ($process.ExitCode -ne 0) {
        throw "WizTree export failed with exit code $($process.ExitCode)."
    }
    if (-not (Test-Path -LiteralPath $OutputPath)) {
        throw "WizTree did not create expected CSV: $OutputPath"
    }
}

try {
    New-Item -ItemType Directory -Path $RunRoot -Force | Out-Null
    $ConfigPath = Join-Path $RunRoot "config.toml"
    $DbPath = Join-Path $RunRoot "disk-audit.sqlite3"
    $ContextPath = Join-Path $RunRoot "agent-context.json"

    if (-not $env:LOCALAPPDATA) { throw "LOCALAPPDATA is not available in this PowerShell session." }
    if ($Mode -eq "scan" -and -not $CsvPath) { Resolve-WizTreeExecutable }
    if (-not $WizTreePath) { $script:WizTreePath = "WizTree64.exe" }
    $PersistentWorkspace = Join-Path $env:LOCALAPPDATA "DiskCleanupSkill"
    $configText = @"
config_version = 1

[tools]
wiztree_executable = "$(Convert-ToTomlPath $WizTreePath)"

[scan]
targets = ["$(Convert-ToTomlPath $Target)"]
retain_scan_count = 1

[storage]
workspace = "$(Convert-ToTomlPath $PersistentWorkspace)"
database_name = "disk-audit.sqlite3"

[logging]
level = "INFO"
retain_days = 1
"@
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($ConfigPath, $configText, $utf8NoBom)

    $env:PYTHONPATH = Join-Path $ProjectRoot "src"

    if ($Mode -eq "clean") {
        if (-not $RunId) { throw "clean requires -RunId" }
        $argsList = @("-m", "disk_cleanup", "--config", $ConfigPath, "clean", "--run-id", $RunId)
        if ($CandidateId) {
            foreach ($id in $CandidateId) { $argsList += @("--candidate-id", $id) }
        }
        elseif ($PlanHash -and $ApprovalCode) {
            $argsList += @("--plan-hash", $PlanHash, "--approval-code", $ApprovalCode)
        }
        else { throw "clean requires -CandidateId, or -PlanHash with -ApprovalCode" }
        & $Python @argsList
        exit $LASTEXITCODE
    }

    $argsList = @("-m", "disk_cleanup", "--config", $ConfigPath, "scan", "--target", $Target)
    if ($CsvPath) { $argsList += @("--csv", $CsvPath) }
    elseif ($WizTreePath -and (Test-Path -LiteralPath $WizTreePath -PathType Leaf)) {
        $argsList += @("--wiztree", $WizTreePath)
    }
    if ($NoOpen) { $argsList += "--no-open" }
    & $Python @argsList
    exit $LASTEXITCODE
}
catch {
    $line = $_.InvocationInfo.ScriptLineNumber
    Write-Error ("disk-cleanup mode '{0}' failed at script line {1}: {2}" -f $Mode, $line, $_.Exception.Message)
    exit 1
}
finally {
    if (Test-Path -LiteralPath $RunRoot) {
        Assert-RunRootIsDisposable $RunRoot
        Remove-Item -LiteralPath $RunRoot -Recurse -Force
    }
}
